### ISSUE TITLE
Undocumented requirement for Python 3.6.x due to use of Fstrings

### ISSUE THREAD

**Issue by mlava** [raetha/wyzesense2mqtt#27]
## Describe the Bug

Hi. Sorry for this noob issue, but I'm struggling to simply get past step 1!

I've installed using the Linux instructions and updated config files etc. If I try to run the python file wyzesense2mqtt.py I get the following error:

```
File "wyzesense2mqtt.py", line 30
    print(f"File error: {str(error)}")
                                    ^
SyntaxError: invalid syntax

```

I vim into the file and see that is related to IO errors.
I therefore wondered if it isn't finding my dongle.

lsusb shows my usb_dongle as:

```
Bus 001 Device 005: ID 1a86:e024 QinHeng Electronics`
```

I therefore changed the python file as shown:

```
   if (CONFIG['usb_dongle'].lower() == "auto"):
        device_list = subprocess.check_output(
                ["ls", "-la", "/sys/class/qinheng"]
        ).decode("utf-8").lower()
        for line in device_list.split("\n"):
            if (("e024" in line) and ("1a86" in line)):
                for device_name in line.split(" "):
                    if ("QinHeng" in device_name):
                        CONFIG['usb_dongle'] = "/dev/%s" % device_name
                        break
```

It appears my dongle has the same ID strings as the config (e024 and 1a86) but this still throws the same error.

I'm not sure what else to try!

### Desktop

RPiW0
Raspbian GNU/Linux 8 (jessie)

Any advice would be gratefully received!

**Comment by raetha** [comment]
Hi @mlava. Based on the error, it looks like it is having trouble parsing one of the YAML config files. If you look just above at line 17 of the script it gives the names that are expected for the config files, along with that it's looking for them in a "config" subfolder. The sensors.yaml file doesn't actually need to exist, but logging.yaml and config.yaml do need to exist. I'm not sure why it's giving a syntax error though. Could you be running this under Python2 by any chance? I didn't test things there, so it might be the syntax doesn't work for the older version of Python.

Anyway, start by checking that the config files are in place and named correctly.

Let me know, would like to help get you through this quickly.

**Comment by mlava** [comment]
@raetha 
Thanks for the fast reply. 
A list of files in /config shows:
config.yaml  logging.yaml  sensors.yaml.sample

vim config.yaml:
```
mqtt_host: 192.168.1.148
mqtt_port: 1883
mqtt_username:
mqtt_password:
mqtt_client_id: wyzesense2mqtt
mqtt_clean_session: false
mqtt_keepalive: 60
mqtt_qos: 2
mqtt_retain: true
self_topic_root: /wyzesense2mqtt
hass_topic_root: /homeassistant
usb_dongle: auto
```

vim logging.yaml:
```
version: 1
formatters:
  simple:
    format: '%(message)s'
  verbose:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
  file:
    backupCount: 7
    class: logging.handlers.TimedRotatingFileHandler
    encoding: utf-8
    filename: logs/wyzesense2mqtt.log
    formatter: verbose
    level: INFO
    when: midnight
root:
  handlers:
    - file
    - console
  level: DEBUG
```

I have both python2 and 3 installed on the Pi.

I ran the .py file with 
`python3 wyzesense2mqtt.py`

Cheers :)
